In [1]:
import gym
import numpy as np
env = gym.make('FrozenLake-v0')

In [26]:
Q = np.zeros([env.observation_space.n,env.action_space.n])
lr=.8
y = 0.95
num_episodes = 2000
reward_list = []
for i in range(num_episodes) :
    s = env.reset()
    reward_All = 0
    d = False
    j = 0
    while j < 99 :
        j+=1
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        s1,r,d,_ = env.step(a)
        Q[s,a] = Q[s,a] + lr * (r + y *(np.max(Q[s1, :] - Q[s,a]))) 
        reward_All += r
        s = s1
        if d == True:
            break
    reward_list.append(reward_All)
print ("Score over time: ")
print (str(sum(reward_list)/num_episodes) ) 
print ("Final Q-Table Values")
print (Q)  

Score over time: 
0.028
Final Q-Table Values
[[  1.54799428e-02   1.45314357e-02   1.79744141e-02   1.06266921e-01]
 [  2.39063468e-03   1.75692455e-03   5.05729122e-03   1.06266921e-01]
 [  2.62818177e-03   2.40517134e-02   7.56912408e-03   1.06266921e-01]
 [  3.59579483e-03   4.44604784e-04   2.94483584e-04   1.06266921e-01]
 [  3.19657864e-01   1.14817223e-03   0.00000000e+00   3.21704735e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  4.37092034e-04   2.05346540e-03   2.05587040e-02   2.78055871e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  7.61517997e-04   0.00000000e+00   6.51283606e-03   2.12645205e-01]
 [  2.38405547e-03   4.76236065e-01   0.00000000e+00   0.00000000e+00]
 [  9.45872015e-01   3.22682744e-03   3.80754253e-03   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.69848371e-03   3.83114963e